### ISSUE TITLE
Convert Script to Text.applescript - Simplified Suggestion

### ISSUE THREAD

**Issue by Wintercypher** [abbeycode/AppleScripts#9]
Hi, 

I came across your script while searching for a solution. Your script inspired me to simplify the process while also being able to maintain git history. As a thank you for the inspiration, I have included the code below. 

```
tell application "Script Editor"
	set doc to open inputFile
	save doc as "text" in inputFile
	tell application "Finder" to set name extension of inputFile to "applescript"
	close front window
end tell
```

This method uses Finder to change the extension of the file which removes the need to move the original file to the trash. This reduces the run time by 20%. I would also suggest putting an extension filter so that only .scpt files are edited. 

Chip

**Comment by abbeycode** [comment]
That's a cool idea. I think the reason I don't overwrite the original is that I often keep the compiled script around. Thanks for making the suggestion, and hopefully people who want to accomplish the same will find this issue.
